/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.grupo;

/**
 *
 * @author ceo_flotuz
 */
public class Grupos extends javax.swing.JPanel {

    /**
     * Creates new form Grupos
     */
    public Grupos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_pane = new javax.swing.JTabbedPane();
        pn_añadirGrupos = new javax.swing.JPanel();
        lbl_carreraAnadir = new javax.swing.JLabel();
        lbl_semestreAnadir = new javax.swing.JLabel();
        lbl_nalumnosAnadir = new javax.swing.JLabel();
        tf_carreraAnadir = new javax.swing.JTextField();
        tf_semestreAnadir = new javax.swing.JTextField();
        tf_alumnosAnadir = new javax.swing.JTextField();
        btn_anadir = new javax.swing.JButton();
        pn_eliminarGrupos = new javax.swing.JPanel();
        pn_delete = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        li_gruposEliminar = new javax.swing.JList<>();
        pn_detallesEliminar = new javax.swing.JPanel();
        lbl_carreraEliminar = new javax.swing.JLabel();
        lbl_semestreEliminar = new javax.swing.JLabel();
        lbl_nalumnosEliminar = new javax.swing.JLabel();
        tf_carreraEliminar = new javax.swing.JTextField();
        tf_semestreEliminar = new javax.swing.JTextField();
        tf_alumnosEliminar = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelarEliminar = new javax.swing.JButton();

        lbl_carreraAnadir.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_carreraAnadir.setText("Carrera");

        lbl_semestreAnadir.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_semestreAnadir.setText("Semestre");

        lbl_nalumnosAnadir.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_nalumnosAnadir.setText("# Alumnos");

        btn_anadir.setText("Añadir");

        javax.swing.GroupLayout pn_añadirGruposLayout = new javax.swing.GroupLayout(pn_añadirGrupos);
        pn_añadirGrupos.setLayout(pn_añadirGruposLayout);
        pn_añadirGruposLayout.setHorizontalGroup(
            pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_añadirGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_añadirGruposLayout.createSequentialGroup()
                        .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_carreraAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nalumnosAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_semestreAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_carreraAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_semestreAnadir, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_alumnosAnadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                    .addComponent(btn_anadir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        pn_añadirGruposLayout.setVerticalGroup(
            pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_añadirGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_carreraAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_carreraAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_semestreAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_semestreAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_añadirGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nalumnosAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_alumnosAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        tb_pane.addTab("Añadir Grupo", pn_añadirGrupos);

        pn_delete.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));

        li_gruposEliminar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Grupo 1", "Grupo 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(li_gruposEliminar);

        javax.swing.GroupLayout pn_deleteLayout = new javax.swing.GroupLayout(pn_delete);
        pn_delete.setLayout(pn_deleteLayout);
        pn_deleteLayout.setHorizontalGroup(
            pn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pn_deleteLayout.setVerticalGroup(
            pn_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_detallesEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));

        lbl_carreraEliminar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_carreraEliminar.setText("Carrera");

        lbl_semestreEliminar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_semestreEliminar.setText("Semestre");

        lbl_nalumnosEliminar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lbl_nalumnosEliminar.setText("# Alumnos");

        tf_carreraEliminar.setEditable(false);

        tf_semestreEliminar.setEditable(false);

        tf_alumnosEliminar.setEditable(false);

        btn_eliminar.setText("Eliminar");

        btn_cancelarEliminar.setText("Cancelar");

        javax.swing.GroupLayout pn_detallesEliminarLayout = new javax.swing.GroupLayout(pn_detallesEliminar);
        pn_detallesEliminar.setLayout(pn_detallesEliminarLayout);
        pn_detallesEliminarLayout.setHorizontalGroup(
            pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detallesEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_carreraEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_carreraEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_semestreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_semestreEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nalumnosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_detallesEliminarLayout.createSequentialGroup()
                        .addComponent(tf_alumnosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        pn_detallesEliminarLayout.setVerticalGroup(
            pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detallesEliminarLayout.createSequentialGroup()
                .addGroup(pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_carreraEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_semestreEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_nalumnosEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_detallesEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_carreraEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_semestreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_alumnosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pn_eliminarGruposLayout = new javax.swing.GroupLayout(pn_eliminarGrupos);
        pn_eliminarGrupos.setLayout(pn_eliminarGruposLayout);
        pn_eliminarGruposLayout.setHorizontalGroup(
            pn_eliminarGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_eliminarGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_detallesEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_eliminarGruposLayout.setVerticalGroup(
            pn_eliminarGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_eliminarGruposLayout.createSequentialGroup()
                .addComponent(pn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_detallesEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tb_pane.addTab("Eliminar Grupos", pn_eliminarGrupos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tb_pane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tb_pane)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anadir;
    private javax.swing.JButton btn_cancelarEliminar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_carreraAnadir;
    private javax.swing.JLabel lbl_carreraEliminar;
    private javax.swing.JLabel lbl_nalumnosAnadir;
    private javax.swing.JLabel lbl_nalumnosEliminar;
    private javax.swing.JLabel lbl_semestreAnadir;
    private javax.swing.JLabel lbl_semestreEliminar;
    private javax.swing.JList<String> li_gruposEliminar;
    private javax.swing.JPanel pn_añadirGrupos;
    private javax.swing.JPanel pn_delete;
    private javax.swing.JPanel pn_detallesEliminar;
    private javax.swing.JPanel pn_eliminarGrupos;
    private javax.swing.JTabbedPane tb_pane;
    private javax.swing.JTextField tf_alumnosAnadir;
    private javax.swing.JTextField tf_alumnosEliminar;
    private javax.swing.JTextField tf_carreraAnadir;
    private javax.swing.JTextField tf_carreraEliminar;
    private javax.swing.JTextField tf_semestreAnadir;
    private javax.swing.JTextField tf_semestreEliminar;
    // End of variables declaration//GEN-END:variables
}
