/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canalizacion;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Emmanuel
 */
public class Canalizacion extends javax.swing.JPanel {

    /**
     * Creates new form Canalizacion
     */
    public Canalizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        pn_nuevaCanalizacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nucaFecha = new javax.swing.JTextField();
        btn_nucaSelecAlumno = new javax.swing.JButton();
        tf_nucaNC = new javax.swing.JTextField();
        btn_nucaSelecTutor = new javax.swing.JButton();
        cbx_carrera = new javax.swing.JComboBox<>();
        cbx_semestre = new javax.swing.JComboBox<>();
        ch_nucaTristeza = new javax.swing.JCheckBox();
        ch_nucaAngustia = new javax.swing.JCheckBox();
        ch_nucaAnsiedad = new javax.swing.JCheckBox();
        ch_nucaDepresion = new javax.swing.JCheckBox();
        ch_nucaLlanto = new javax.swing.JCheckBox();
        ch_nucaConducta = new javax.swing.JCheckBox();
        ch_nucaEstadoAnimo = new javax.swing.JCheckBox();
        ch_nucaExitación = new javax.swing.JCheckBox();
        ch_nucaIrritabilidad = new javax.swing.JCheckBox();
        ch_nucaDrogas = new javax.swing.JCheckBox();
        ch_nucaAprendizaje = new javax.swing.JCheckBox();
        ch_nucaAgresiones = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        tf_nucaOtros = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_nucaDescripcion = new javax.swing.JTextArea();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nueva Canalización");

        jLabel2.setText("Fecha");

        jLabel3.setText("Alumno");

        jLabel4.setText("NC");

        jLabel5.setText("Tutor");

        jLabel6.setText("Carrera");

        jLabel7.setText("Semestre");

        btn_nucaSelecAlumno.setText("Seleccionar alumno..");
        btn_nucaSelecAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nucaSelecAlumnoActionPerformed(evt);
            }
        });

        btn_nucaSelecTutor.setText("Seleccionar tutor..");

        cbx_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "Itics", "Sistemas", "Informatica" }));

        cbx_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ch_nucaTristeza.setText("Tristeza profunda o constante");

        ch_nucaAngustia.setText("Angustia");

        ch_nucaAnsiedad.setText("Ansiedad");

        ch_nucaDepresion.setText("Desesperación constante");

        ch_nucaLlanto.setText("Llanto súbito continuo");

        ch_nucaConducta.setText("Cambios bruscos de conducta");

        ch_nucaEstadoAnimo.setText("Cambios subitos de estado de animo");

        ch_nucaExitación.setText("Excitación o alteración psicomotriz");

        ch_nucaIrritabilidad.setText("Irritabilidad constante sin motivo aparente");

        ch_nucaDrogas.setText("Consumo de drogas");

        ch_nucaAprendizaje.setText("Dificultades severas de aprendizaje");

        ch_nucaAgresiones.setText("Auto agresiones");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Otros:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Desarrollo del problema (Si conoce la situación de origen describala brevemente)");

        ta_nucaDescripcion.setColumns(20);
        ta_nucaDescripcion.setRows(5);
        jScrollPane1.setViewportView(ta_nucaDescripcion);

        btn_aceptar.setText("Aceptar");

        btn_cancelar.setText("Cancelar");

        javax.swing.GroupLayout pn_nuevaCanalizacionLayout = new javax.swing.GroupLayout(pn_nuevaCanalizacion);
        pn_nuevaCanalizacion.setLayout(pn_nuevaCanalizacionLayout);
        pn_nuevaCanalizacionLayout.setHorizontalGroup(
            pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                        .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nucaNC))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_nucaFecha)
                                            .addComponent(btn_nucaSelecAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_nucaSelecTutor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_carrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_semestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(95, 95, 95)
                                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ch_nucaTristeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaAngustia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaAnsiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaDepresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaLlanto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaConducta, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ch_nucaEstadoAnimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaExitación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaIrritabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaDrogas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaAprendizaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ch_nucaAgresiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nucaOtros))))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_nuevaCanalizacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_nuevaCanalizacionLayout.setVerticalGroup(
            pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nuevaCanalizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nucaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_nucaTristeza)
                    .addComponent(ch_nucaEstadoAnimo))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_nucaSelecAlumno)
                    .addComponent(ch_nucaAngustia)
                    .addComponent(ch_nucaExitación))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nucaNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_nucaAnsiedad)
                    .addComponent(ch_nucaIrritabilidad))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ch_nucaDepresion)
                    .addComponent(ch_nucaDrogas)
                    .addComponent(btn_nucaSelecTutor))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_nucaLlanto)
                    .addComponent(ch_nucaAprendizaje))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch_nucaConducta)
                    .addComponent(ch_nucaAgresiones))
                .addGap(18, 18, 18)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nucaOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_nuevaCanalizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(pn_nuevaCanalizacion);

        jTabbedPane1.addTab("Nueva Canalizacion", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nucaSelecAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nucaSelecAlumnoActionPerformed
        //Se muestra el panel de seleccionar alumno
        Seleccionar_alumno seleccionar = new Seleccionar_alumno();
        
        
        //Se muestra un panel donde se selecciona el alumno
        JOptionPane.showInternalMessageDialog(this,seleccionar);
        
        //Se obtiene alumno seleccionado
        String alumno = seleccionar.getAlumnoSeleccioando();
        //ësto es de prueba nah más
        btn_nucaSelecAlumno.setText(alumno.substring(2, 10));
    }//GEN-LAST:event_btn_nucaSelecAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_nucaSelecAlumno;
    private javax.swing.JButton btn_nucaSelecTutor;
    private javax.swing.JComboBox<String> cbx_carrera;
    private javax.swing.JComboBox<String> cbx_semestre;
    private javax.swing.JCheckBox ch_nucaAgresiones;
    private javax.swing.JCheckBox ch_nucaAngustia;
    private javax.swing.JCheckBox ch_nucaAnsiedad;
    private javax.swing.JCheckBox ch_nucaAprendizaje;
    private javax.swing.JCheckBox ch_nucaConducta;
    private javax.swing.JCheckBox ch_nucaDepresion;
    private javax.swing.JCheckBox ch_nucaDrogas;
    private javax.swing.JCheckBox ch_nucaEstadoAnimo;
    private javax.swing.JCheckBox ch_nucaExitación;
    private javax.swing.JCheckBox ch_nucaIrritabilidad;
    private javax.swing.JCheckBox ch_nucaLlanto;
    private javax.swing.JCheckBox ch_nucaTristeza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pn_nuevaCanalizacion;
    private javax.swing.JTextArea ta_nucaDescripcion;
    private javax.swing.JTextField tf_nucaFecha;
    private javax.swing.JTextField tf_nucaNC;
    private javax.swing.JTextField tf_nucaOtros;
    // End of variables declaration//GEN-END:variables
}
